name = "OpenEMS"
uuid = "339106f3-2234-4f9d-9695-73fbe15532b1"
version = "0.1.0"
authors = ["Kaj Wiik <kaj.wiik@iki.fi>"]

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
HDF5 = "0.17.2"
JLD2 = "0.6.3"
PhysicalConstants = "0.2.4"
PythonCall = "0.9.30"
Unitful = "1.25.1"
