name = "OpenEMS"
uuid = "339106f3-2234-4f9d-9695-73fbe15532b1"
version = "0.1.0"
authors = ["Kaj Wiik <kaj.wiik@iki.fi>"]

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
HDF5 = "0.17.2"
JLD2 = "0.6.3"
PythonCall = "0.9.30"
